name: ci
on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - develop

defaults:
  run:
    working-directory: ./glox/

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 'latest'
          check-latest: true
      - run: go version

      - name: Format
        run: go fmt

      - name: Static Analysis
        run: go vet

      - name: Test
        run: go test ./... -v
